### ISSUE TITLE
Replacement of the deprecated attribute "db.user"

### ISSUE THREAD

**Issue by AastikVerma** [open-telemetry/semantic-conventions#1323] opened 2024-08-07 05:30 UTC
I was going through the list of DB deprecated attributes and observed that "db.user" has been marked as deprecated with the description saying "Deprecated, no replacement at this time".
By "no replacement at this time", I'm assuming that a potential replacement for the same might be introduced in the future? OR
Has it been completely deprecated with NO possibility of an attribute being introduced later on that can be used in its place?

**Comment by lmolkova** [comment] 2024-08-09 20:28
Thanks for reporting this @AastikVerma !

I'm going to close this as duplicate of #1142. Could you please answer a few questions (on that issue):

- what would be the use-case for `db.user`? How do you want to use it?
- what information you'd want to see there?
- is it related to a certain database or multiple database systems?

Thank you!

**Closed by lmolkova** 2024-08-09 20:28 UTC
