### ISSUE TITLE
required system uptime metric to the semantic conventions that will describe the system uptime. 

### ISSUE THREAD

**Issue by bhupenbisht** [open-telemetry/semantic-conventions#747] opened 2024-02-14 11:38 UTC
We are not getting system uptime for server(windows,linux) hostmetrics. as a metric that measures the uptime of the system. For host observability purpose uptime should be scrap.

**Comment by joaopgrassi** [comment] 2024-02-14 14:24
Hi @bhupenbisht I think this is a duplicate of #648. Please take a look, and if yes I will close this.

**Comment by bhupenbisht** [comment] 2024-02-14 16:43
Hi @joaopgrassi yes.. its same requirement. Could you please confirm if this is available..?

**Comment by joaopgrassi** [comment] 2024-02-20 10:10
Close as dup of #648

**Closed by joaopgrassi** 2024-02-20 10:10 UTC
