### ISSUE TITLE
Use consistent suffix for JVM Metrics 

### ISSUE THREAD

**Issue by lenin-jaganathan** [open-telemetry/semantic-conventions#288] opened 2023-08-29 06:12 UTC
While going through https://github.com/open-telemetry/semantic-conventions/blob/4bbb8c907402caa90bc077214e8a2c78807c1ab9/docs/jvm/jvm-metrics.md?plain=1#L15-L38, it seems like the suffices for some of the metrics seem to be inconsistent with one another and are also not so straight forward.

I propose replacing the suffix "usage" (noun) in the following metrics with "used" (verb),

- jvm.memory.usage
- jvm.memory.usage_after_last_gc
- jvm.buffer.memory.usage

All these represent the amount being used. In addition, the description already uses the word "used" to describe these metrics and the JMX methods also use the word "used". Also, the sibling metrics use the verb form. E.g: "jvm.memory.committed"

**Comment by trask** [comment] 2023-08-31 01:44
hi @lenin-jaganathan!

`.usage` is a common suffix used in otel semconv, check out
* https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-naming
* https://github.com/open-telemetry/semantic-conventions/issues/211#issuecomment-1650388098

so we would probably need to have that discussion (`usage` -> `used`) more broadly than only JVM metrics

I personally think either nouns or adjectives (when it describes the namespace which is a noun) seem like good metric names, e.g.
* `jvm.memory.committed` - measure "committed memory"
* `jvm.class.loaded` - measures "loaded classes"

**Comment by trask** [comment] 2023-10-19 15:58
I realized, I don't think we would want to rename `usage` -> `used` generally, e.g. [`system.memory.usage`](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md#metric-systemmemoryusage) has dimensions:

* total
* used <--
* free
* shared
* buffers
* cached

@lenin-jaganathan wdyt? do you want to keep this issue open? thx

**Comment by lenin-jaganathan** [comment] 2023-10-23 15:14
I would still like this to be addressed. There is a subtle difference between `system.memory.usage` and `jvm.memory.usage`.

As you mentioned, the first metric has multiple states - used, free, cached, etc. But the JVM metric is all about using part of it and we have separate metrics for committed, limit, etc. But even in the system metrics use-case, `total` as a dimension is always a questionable choice since we would expect adding up all the dimensions should be total.

**Comment by trask** [comment] 2023-10-24 01:22
> But even in the system metrics use-case, `total` as a dimension is always a questionable choice since we would expect adding up all the dimensions should be total.

ya, this is being addressed in #409:

> Removes `total` from list of well-known values for `system.memory.state`

can you re-summarize your reasoning for renaming `jvm.memory.usage` to `jvm.memory.used`? I think that will help focus this issue, since we've discussed a few different things above, thx

**Comment by trask** [comment] 2023-11-09 16:10
ah, I think I understand now

`jvm.memory.usage` isn't really a parallel to `system.memory.usage`, since `jvm.memory.usage` is only one dimension of "usage", namely the `used` dimension

**Comment by trask** [comment] 2023-11-09 16:13
same would apply to
* [jvm.memory.usage_after_last_gc](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/runtime/jvm-metrics.md#metric-jvmmemoryusage_after_last_gc)
* [jvm.buffer.memory.usage](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/runtime/jvm-metrics.md#metric-jvmbuffermemoryusage)

**Comment by trask** [comment] 2023-11-09 16:26
looking at other `*.usage` metrics
* `db.client.connections.usage` / `db.client.connections.limit`
  * has `state` dimension (`used` / `idle`)
* `hw.gpu.memory.usage` / `hw.gpu.memory.limit`
  * **no state dimension <---**
* `hw.logical_disk.usage` / `hw.logical_disk.utilization` / `hw.logical_disk.limit`
  * has `state` dimension (`used` / `free`)
* `process.memory.usage`
  * **no state dimension <---**
* `system.memory.usage` / `system.memory.utilization`
  * has `state` dimension (`used` / `free` / `shared` / `buffers` / `cached`)
* `system.paging.usage` / `system.paging.utilization`
  * has `state` dimension (`used` / `free`)
* `system.filesystem.usage` / `system.filesystem.utilization`
  * has `state` dimension (`used` / `free` / `reserved`)

**Comment by trask** [comment] 2023-11-13 02:43
There seem to be two options for `jvm.memory.usage`:

### Option 1

Rename `jvm.memory.usage` to `jvm.memory.used`

### Option 2

Keep the name, but add `jvm.memory.state` dimension:
* `used`
* `free` (which would be committed minus used)

and remove the `jvm.memory.committed` metric

**Comment by trask** [comment] 2023-11-15 00:21
I don't think I got Option 2 right above.

I think `free` should be `jvm.memory.limit` minus `used`, see https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-naming:

> **usage** - an instrument that measures an amount used out of a known total (**limit**) amount should be called `entity.usage`. For example, `system.memory.usage` with attribute `state = used | cached | free | ...` for the amount of memory in a each state. Where appropriate, the sum of **usage** over all attribute values SHOULD be equal to the **limit**.

In which case we'd probably leave `jvm.memory.committed` metric as-is.

**Comment by trask** [comment] 2023-11-17 00:34
Discussed in Java SIG meeting today:

* Not all memory pools have a limit, and so `jvm.memory.usage` doesn't follow the conventions for `.usage` (https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-naming):

  > an instrument that measures an amount used out of a known total (limit) amount
* We could still introduce `free` dimension for pools which have a limit, but we think `free` will be confusing if we define it as `limit - used` since there is some precedence in the Java that `free = committed - used` (https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#freeMemory--)

**Comment by lenin-jaganathan** [comment] 2024-07-19 17:24
@trask / @joaopgrassi Do you guys think `jvm.buffer.memory.usage` was missed as part of this change?

The metric is still experimental which should allow the re-naming.

**Comment by trask** [comment] 2024-07-19 17:55
yes I think it was missed, re-opening, if you'd like to send a PR that would be great!

**Comment by lenin-jaganathan** [comment] 2024-07-19 19:19
Submitted https://github.com/open-telemetry/semantic-conventions/pull/1265. Will follow it up with one for Java instrumentation once the sem-conv is merged.

**Comment by joaopgrassi** [comment] 2024-07-25 11:29
What about the other metrics mentioned above:

> [jvm.memory.usage_after_last_gc](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/runtime/jvm-metrics.md?rgh-link-date=2023-11-09T16%3A13%3A50Z#metric-jvmmemoryusage_after_last_gc)
    [jvm.buffer.memory.usage](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/runtime/jvm-metrics.md?rgh-link-date=2023-11-09T16%3A13%3A50Z#metric-jvmbuffermemoryusage)
    
Are those also suppose to change? Just want to make sure the issue isn't closed again once https://github.com/open-telemetry/semantic-conventions/pull/1265 is merged.

**Comment by lenin-jaganathan** [comment] 2024-07-25 12:09
@joaopgrassi The first 2 metrics memory.usage/memory.usage_after_last_gc where already changed before JVM sem conv stabilisation. Only, jvm.buffer.usage was left behind.

**Closed** 2024-07-29 15:21 UTC
